version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: gravygaming/aspnetcore-yarn-build
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: quizjam-boards-{{ .Branch }}-{{ checksum "src/QuizJam.Boards.csproj" }}
      - run:
          name: Dependencies
          command: sh script/update
      - run:
          name: Build
          command: sh script/build
      # - run:
      #     name: Test
      #     working_directory: test/ContactManager.Api.IntegrationTests
      #     command: dotnet xunit
      - run:
          name: Publish Artifacts
          command: dotnet publish src/QuizJam.Boards.csproj --configuration Release
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.04.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: List After
          command: ls -la
      - save_cache:
          key: quizjam-boards-{{ .Branch }}-{{ checksum "src/QuizJam.Boards.csproj" }}
          paths:
            - ~/.nuget
      - store_artifacts:
          path: src/bin/Release/netcoreapp2.0/publish/
      - deploy:
          name: Deploy production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t quizjam-boards .
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              docker tag quizjam-boards gravygaming/quizjam-boards:latest
              docker push gravygaming/quizjam-boards
            fi
