version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: gravygaming/aspnetcore-yarn-build
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: aspnetcore-yarn-build-{{ .Branch }}-{{ checksum "Dockerfile" }}
      - run:
          name: Build
          command: sh script/build
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.04.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: List After
          command: ls -la
      - save_cache:
          key: qaspnetcore-yarn-build-{{ .Branch }}-{{ checksum "Dockerfile" }}
          paths:
            - ~/.nuget
      - deploy:
          name: Deploy production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t aspnetcore-yarn-build .
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
              docker tag aspnetcore-yarn-build gravygaming/aspnetcore-yarn-build:latest
              docker push gravygaming/aspnetcore-yarn-build
            fi
